# Generated by Django 4.0.5 on 2023-04-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='perfil/default.png', null=True, upload_to='perfil/'),
        ),
    ]
