# Generated by Django 4.0.5 on 2022-12-29 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_remove_user_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_administrator',
            new_name='is_staff',
        ),
    ]
