# Generated by Django 4.0.5 on 2023-08-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apunte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='document',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
