# Generated by Django 4.0.5 on 2023-08-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apunte', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
