# Generated by Django 4.0.5 on 2022-11-06 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apunte', '0005_remove_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='id_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='apunte.order'),
        ),
    ]
