# Generated by Django 4.0.5 on 2022-11-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apunte', '0006_alter_detail_id_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='subTotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='subTotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
